title: Celebrity Top 1
description: Berita Selebriti & Hiburan Terkini
baseurl: "" 
url: "https://username.github.io" # GANTI 'username' DENGAN USERNAME GITHUB ANDA

theme: minima # Kita pakai tema default dulu biar cepat, nanti bisa diganti custom

# Pengaturan Markdown
markdown: kramdown

# Default Layout untuk semua post
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
