title: Celebrity Top 1
description: Berita Selebriti Terkini

# Ini penting agar GitHub tahu kita pakai Jekyll
markdown: kramdown

# Pengaturan default untuk semua file di folder _posts
defaults:
  - scope:
      path: "posts"
    values:
      layout: "posts"
